services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
       - /Users/user/postgres/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Users
    restart: always
    networks:
      - app-network
volumes:
  db:

networks:
  app-network:
    driver: bridge

